### ISSUE TITLE
Migrate ES5 to ES6 syntax

### ISSUE THREAD

**Issue by Jessica7** [notwaldorf/doodle#10]
Hi Monica, Would you like migrate your project to ES6 syntax?

**Comment by notwaldorf** [comment]
Thanks for asking! Not particularly, since that means it won't work on IE11, and i don't think it would add any real benefit -- it's just a bunch of global functions :(

**Comment by Jessica7** [comment]
Yeah, I agree! Thanks very much for answer :D I have been using ES6 and babelJS for cross-browser detection in my projects, It's amazing. I liked your project :purple_heart:

**Comment by notwaldorf** [comment]
Yay thanks! Fingers crossed for the future where we can write ES6 and it will work on all the browsers! 🎉
